export const dataProperties = [
  {
    id: 1,
    location: "Calle del Bosque Encantado 42, Paraná, ER",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie1.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "Encantadora casa en la tranquila Calle del Bosque Encantado. Este hermoso piso de 430 metros cuadrados tiene 3 habitaciones y 1 baño, combinando comodidad y elegancia en un entorno natural único. Situada en una zona mágica y bien comunicada, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 2,
    location: "Avenida de las Mariposas 789, Federación, ER",
    price: 150000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie2.jpeg",
    star: 4,
    meters: 230,
    description:
      "Elegante residencia en la hermosa Avenida de las Mariposas. Este encantador piso de 230 metros cuadrados cuenta con 2 habitaciones y 2 baños, combinando comodidad y estilo en un entorno natural inigualable. Ubicada en una zona vibrante y bien comunicada, esta vivienda es un oasis de paz y belleza. Al ingresar, serás recibido por un amplio recibidor que te llevará a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te sumergirás en un generoso salón comedor que se conecta con la cocina a través de puertas correderas.",
  },
  {
    id: 3,
    location: "Calle de los Sueños 567, Nogoyá, ER",
    price: 135000,
    bedrooms: 5,
    bathroom: 2,
    image: "propertie3.jpeg",
    star: 5,
    meters: 90,
    description:
      "Encantadora residencia en la pintoresca Calle de los Sueños. Este espectacular piso de 90 metros cuadrados ofrece 5 habitaciones y 2 baños, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Gualeguay, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 4,
    location: "Avenida del Sol 321, La Paz, ER",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie4.jpeg",
    star: 4.2,
    meters: 120,
    description:
      "Espectacular residencia en la soleada Avenida del Sol. Este hermoso piso de 120 metros cuadrados cuenta con 3 habitaciones y 1 baño, combinando comodidad y elegancia en un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en La Paz, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 5,
    location: "Calle de la Armonía 789, Villa Paranacito, ER",
    price: 180000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie5.jpeg",
    star: 4.1,
    meters: 87,
    description:
      "Hermosa residencia en la serena Calle de la Armonía. Este encantador piso de 87 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Villaguay, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 6,
    location: "Avenida de la Tranquilidad 456, Gualeguaychú, ER",
    price: 165000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie6.jpeg",
    star: 3.7,
    meters: 220,
    description:
      "Residencia única en la apacible Avenida de la Tranquilidad. Este espectacular piso de 220 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Gualeguaychú, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 7,
    location: "Calle del Encanto 987, La Paz, ER",
    price: 212000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie7.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "Encantadora casa en la mágica Calle del Encanto. Este hermoso piso de 430 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en La Paz, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 8,
    location: "Calle de la Serenidad 654, Oro Verde, ER",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie8.jpeg",
    star: 4.5,
    meters: 330,
    description:
      "Residencia encantadora en la serena Calle de la Serenidad. Este hermoso piso de 330 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Concordia, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 9,
    location: "Avenida de las Maravillas 123, Gualeguay, ER",
    price: 205000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie9.jpeg",
    star: 4.5,
    meters: 380,
    description:
      "Residencia espectacular en la sorprendente Avenida de las Maravillas. Este impresionante piso de 380 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Gualeguay, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 10,
    location: "Avenida de los Sueños 789, Villaguay, ER",
    price: 195000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie10.jpeg",
    star: 4.1,
    meters: 270,
    description:
      "Hermosa residencia en la soñada Avenida de los Sueños. Este encantador piso de 270 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Villaguay, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 11,
    location: "Calle de los Deseos 456, Cerrito, ER",
    price: 200000,
    bedrooms: 2,
    bathroom: 1,
    image: "propertie11.jpeg",
    star: 5,
    meters: 430,
    description:
      "Residencia única en la deseada Calle de los Deseos. Este espectacular piso de 430 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Concordia, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 12,
    location: "Avenida de la Fantasía 987, Diamante, ER",
    price: 230000,
    bedrooms: 4,
    bathroom: 1,
    image: "propertie12.jpeg",
    star: 3.9,
    meters: 76,
    description:
      "Residencia encantadora en la fantástica Avenida de la Fantasía. Este hermoso piso de 76 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Gualeguaychú, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 13,
    location: "Calle de la Ilusión 654, Victoria, ER",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie13.jpeg",
    star: 4.8,
    meters: 290,
    description:
      "Hermosa residencia en la ilusionante Calle de la Ilusión. Este encantador piso de 290 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en La Paz, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 14,
    location: "Avenida de la Esperanza 123, Concordia, ER",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie14.jpeg",
    star: 4.9,
    meters: 180,
    description:
      "Residencia espectacular en la esperanzadora Avenida de la Esperanza. Este impresionante piso de 180 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Concordia, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 15,
    location: "Calle de las Flores 456, Colón, ER",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie15.jpeg",
    star: 4.1,
    meters: 287,
    description:
      "Encantadora casa en la colorida Calle de las Flores. Este hermoso piso de 287 metros cuadrados ofrece 3 habitaciones y 1 baño, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Colón, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
  {
    id: 16,
    location: "Calle de la Luna Llena 123, Concepcion del Uruguay, ER",
    price: 200000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie16.jpeg",
    star: 4,
    meters: 290,
    description:
      "Increíble residencia en la pintoresca Calle de la Luna Llena. Este espectacular piso de 290 metros cuadrados ofrece 3 habitaciones y 2 baños, combinando comodidad, elegancia y un entorno natural inigualable. Ubicada en una zona tranquila y bien comunicada en Gualeguaychú, esta vivienda es un refugio de paz y belleza. Al entrar, serás recibido por un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor que se fusiona con la cocina a través de puertas correderas.",
  },
];